#!/bin/bash
if [[ $EUID -ne 0 ]]; then
      echo "This script must be run as root" 1>&2
      exit 1
    fi


# Config


#
# Adjust your settings here !!! 
#

# Automatic NIC name retrieval
nic=$(find /sys/class/net ! -type d | xargs --max-args=1 realpath  | awk -F\/ '/pci/{print $NF}')
# IPv4 Gatway
gwv4=10.0.0.10
# IPv6 Gateway
gwv6=2a06:1111:1111:1111::10
# Subnet IPv4 (Note that the last octet is missing, which is asked when running the script)
subnetv4=10.0.0.
# Subnet IPv6 (Note that the last octet is missing, which is asked when running the script)
subnetv6=2a06:1111:1111:1111::
# IPv4 Pointopoint Address which equals the IPv4 Gateway (Required by Hetzner)
p2p=10.0.0.10
# IPv6 subnet size
netmask=64


# 
# No changes after this line !!!
#


read -e -p "Enter Hostname: " hostname
read -e -p "Enter IPv4: " -i $subnetv4 ipv4
read -e -p "Enter IPv6: " -i $subnetv6 ipv6



# Backup configs

cp /etc/network/interfaces /etc/network/interfaces.bak
cp /etc/hosts /etc/hosts.bak
cp /etc/hostname /etc/hostname.bak


# Set hostname

echo $hostname > /etc/hostname
echo "$ipv4 $hostname $hostname
      $ipv6 $hostname $hostname
      127.0.0.1 localhost
      ::1 ip6-localhost ip6-loopback
      fe00::0 ip6-localnet
      ff00::0 ip6-mcastprefix
      ff02::1 ip6-allnodes
      ff02::2 ip6-allrouters
      ff02::3 ip6-allhosts" > /etc/hosts
hostname -F /etc/hostname


# Network config

# Check if user submited an IPv4 and IPv6 address. If both exist: Dualstack; If only IPv6: IPv6 only

if [ "$subnetv4" == "$ipv4" ]
    then

      # IPv6 only
      echo "auto lo
                iface lo inet loopback

            auto $nic
            iface $nic inet6 static
                address $ipv6
                netmask $netmask
                gateway $gwv6" > /etc/network/interfaces
    else

      # Dualstack
      echo "auto lo
                iface lo inet loopback

            auto $nic
                iface $nic inet static
                address $ipv4
                gateway $gwv4
                pointopoint $p2p
                dns-nameservers 8.8.8.8 8.8.4.4
            iface $nic inet6 static
                address $ipv6
                netmask $netmask
                gateway $gwv6" > /etc/network/interfaces
    fi
reboot
